### PR TITLE
fix: clean up conversations

### LINKED ISSUE #63: Plugin crashes when using MongoDB session adapter
I'm using [MongoDB session adapter](https://github.com/grammyjs/storages/tree/main/packages/mongodb)  like this:

```
interface SessionData {
    counter: number
}

type MyContext = Context &  ConversationFlavor & SessionFlavor<SessionData>

const sessions = mongoose.connection.db.collection<ISession>("sessions");
// ....

bot.use(session({
        initial: () => ({ counter: 1}),
        storage: new MongoDBAdapter<SessionData>({ collection: sessions }),
    }));

 bot.use(conversations<MyContext>());
 bot.use(createConversation<MyContext>(setStartConversation, 'setStart'));
 bot.use(createConversation<MyContext>(noStartConversation));
```

So the bot crashes on a first update with the message:

```
Error in middleware while handling update 611149669 TypeError: Cannot read properties of null (reading 'forEach')
    at ConversationHandle._replayWait (/home/danny/local/qmbotjs/node_modules/@grammyjs/conversations/out/conversation.js:451:15)
    at run (/home/danny/local/qmbotjs/node_modules/@grammyjs/conversations/out/conversation.js:204:45)
    at runUntilComplete (/home/danny/local/qmbotjs/node_modules/@grammyjs/conversations/out/conversation.js:312:32)
    at /home/danny/local/qmbotjs/node_modules/@grammyjs/conversations/out/conversation.js:359:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/danny/local/qmbotjs/node_modules/grammy/out/composer.js:61:13
    at async /home/danny/local/qmbotjs/node_modules/@grammyjs/conversations/out/conversation.js:267:9
    at async /home/danny/local/qmbotjs/node_modules/grammy/out/composer.js:61:13
    at async /home/danny/local/qmbotjs/node_modules/grammy/out/convenience/session.js:65:9
    at async /home/danny/local/qmbotjs/node_modules/grammy/out/composer.js:61:13
```

If using default memory session adapter, everything is smooth.

### PR DESCRIPTION
**Pull request by ndatg**
I use **MongoDBAdapter** for sessions. 

The `conversation` field in db becomes `null` when you exit the conversation. The code contains a strict check for `undefined`.
Got an error: `TypeError: Cannot convert undefined or null to object`.
Made some minor fix.

Fixes #63.

### CODE REVIEW

File: src/conversation.ts [hunk 1]
```diff
@@ -242,7 +242,7 @@ class ConversationControls {
      */
     public async exit(id?: string) {
         const session = await this[internal].session();
-        if (session.conversation === undefined) return;
+        if (session.conversation == undefined) return;
```
Comment (KnorpelSenf) [inline src/conversation.ts:245]: Can you change this?
```suggestion
        if (session.conversation == null) return;
```
This would be consistent with the rest of the code in the grammY ecosystem, and it makes it a bit easier to spot the coercion because null comparisons are so uncommon.

File: src/conversation.ts [hunk 2]
```diff
@@ -472,7 +472,7 @@ export function conversations<C extends Context>(): MiddlewareFn<
         await next();
         if (transformed) {
             const session = await ctx.session;
-            if (session.conversation !== undefined) {
+            if (session.conversation != undefined) {
```
Comment (KnorpelSenf) [inline src/conversation.ts:475]:
```suggestion
            if (session.conversation != null) {
```

File: src/conversation.ts [hunk 3]
```diff
@@ -615,7 +615,7 @@ export function createConversation<C extends Context>(
         } finally {
             // Clean up if no conversations remain
             if (
-                session.conversation !== undefined &&
+                session.conversation != undefined &&
```
Comment (KnorpelSenf) [inline src/conversation.ts:618]:
```suggestion
                session.conversation != null &&
```

**Review by KnorpelSenf — CHANGES_REQUESTED** [review]
Thank you so much! This was desperately needed.

I just have a few minor nitpicks about code style which you could not be aware of.

(Sorry for the long time to respond btw.)

**Review by KnorpelSenf — APPROVED** [review]
LGTM, thank you!

**Comment by KnorpelSenf** [comment]
CI will need to be fixed before this can be merged. I won't do this tonight.

If you feel like looking into that, consider opening a second pull request. As soon as it's merged, we can sync this one with the upstream branch to fix CI. The changes performed here look good already.

**Review by KnorpelSenf — APPROVED** [review]
LGTM. Thanks!
